version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bitcoin_postgres
    restart: always
    environment:
      POSTGRES_DB: bitcoin_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bitcoin_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  mlflow:
    image: python:3.12-slim
    container_name: bitcoin_mlflow
    restart: always
    ports:
      - "5001:5001"
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    command: >
      sh -c "pip install mlflow boto3 &&
             mlflow server --host 0.0.0.0 --port 5001 --backend-store-uri file:///mlflow --default-artifact-root s3://mlflow/ --serve-artifacts"
    volumes:
      - mlflow_data:/mlflow
    depends_on:
      - minio

  minio:
    image: minio/minio
    container_name: bitcoin_minio
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
  mlflow_data:
